import React from 'react';

export const ICONS_MAP = {
    "http://onto.fel.cvut.cz/ontologies/lib/module/improve-spo-with-marginals":"battery.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/import-e5x":"angle-up.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/construct-form-metadata":"arrow-left.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/apply-construct-with-chunked-values":"black-tie.png",
    "http://topbraid.org/sparqlmotionlib#ReturnRDF":"500px.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/cli":"arrow-down.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/tarql":"behance.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/apply-construct-with-chunked-values-and-scrollable-cursor":"audio-description.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/sparql-endpoint-download-graph":"address-book-o.png",
    "http://topbraid.org/sparqlmotionlib#BindBySelect":"archive.png",
    "http://topbraid.org/sparqlmotion#inbas-adapter-module":"backward.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/bind-rdf-content-hash":"apple.png",
    "http://topbraid.org/sparqlmotionlib#ApplyConstruct":"address-book.png",
    "http://topbraid.org/sparqlmotion#kbss-adapter-module":"automobile.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/deploy":"battery-0.png",
    "http://topbraid.org/sparqlmotionlib#Merge":"braille.png",
    "http://topbraid.org/sparqlmotionlib#ExportToRDFFile":"bitcoin.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/temporal-v1":"bed.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/apply-construct-with-scrollable-cursor":"briefcase.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/form-generator":"beer.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/external-schemex":"arrow-right.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/void":"bitbucket-square.png",
    "http://topbraid.org/sparqlmotionlib#PerformUpdate":"american-sign-language-interpreting.png",
    "http://onto.fel.cvut.cz/ontologies/lib/module/sparql-endpoint-retrieve-graph":"anchor.png",
    "http://topbraid.org/sparqlmotionlib#BindWithConstant":"btc.png",
}
