services:
  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:${INTERNAL_HOST_PORT:-1235}:80"
    restart: unless-stopped
    depends_on:
      - s-pipes-engine
      - s-pipes-editor-rest
      - db-server
      - s-pipes-editor-ui
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
      APP_ORIGIN: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}"
      SPIPES_EDITOR_REST_SERVICE_URL: "${SPIPES_EDITOR_REST_URL:-http://s-pipes-editor-rest:18115}"
      SPIPES_ENGINE_URL: "${SPIPES_ENGINE_URL:-http://s-pipes-engine:8080/s-pipes}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/error.html:/usr/share/nginx/html/error.html:ro

  s-pipes-editor-ui:
    image: "ghcr.io/kbss-cvut/s-pipes-editor-ui/s-pipes-editor-ui:latest"
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - s-pipes-editor-rest
    environment:
      S_PIPES_EDITOR_API_URL: "${SPIPES_EDITOR_REST_URL:-http://localhost:1235/rest}"

  s-pipes-editor-rest:
    #    <<: *s-pipes-editor-rest-dev-port
    image: "ghcr.io/kbss-cvut/s-pipes-editor/s-pipes-editor:latest"
    expose:
      - "18115"
    restart: unless-stopped
    depends_on:
      - s-pipes-engine
      - db-server
    environment:
      SCRIPTPATHS: "${SCRIPTPATHS:-${PWD}/../../s-pipes-modules;${CUSTOM_SCRIPT_PATHS:-${PWD}/../../s-pipes/doc/examples}}"
      SCRIPTRULES: "${SCRIPTRULES:-${PWD}/../../s-pipes-editor/src/main/resources/rules}"
      ENGINEURL: "${SPIPES_ENGINE_URL:-http://s-pipes-engine:8080/s-pipes}/"
      RDF4J_REPOSITORYURL: "${RDF4J_SERVER_URL:-http://db-server:7200}/repositories"
      RDF4J_REPOSITORYNAME: "${RDF4J_REPOSITORYNAME:-s-pipes-execution-log}"
      RDF4J_PCONFIGURL: "${RDF4J_PCONFIGURL:-${PWD}/../../s-pipes-editor-ui/deploy/s-pipes-engine/config.ttl}"
    volumes:
      - /tmp:/tmp
      - ${SHARED_ROOT:-/home}:${SHARED_ROOT:-/home}
      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/

  s-pipes-engine:
    image: "ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest"
    expose:
      - "8080"
    restart: unless-stopped
    depends_on:
      - db-server
    environment:
      CONTEXTS_SCRIPTPATHS: "${SCRIPTPATHS:-${PWD}/../../s-pipes-modules;${CUSTOM_SCRIPT_PATHS:-${PWD}/../../s-pipes/doc/examples}}"
    volumes:
      - /tmp:/tmp
      - ${SHARED_ROOT:-/home}:${SHARED_ROOT:-/home}
      - /usr/local/tomcat/temp/:/usr/local/tomcat/temp/

  db-server:
    build:
      context: ./db-server
    expose:
      - "7200"
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: "-Dgraphdb.external-url=${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}/services/db-server"
    volumes:
      - ./db-server/init-config:/repo-config:ro
      - db-server:/opt/graphdb/home

volumes:
  data:
  logs:
  db-server:
