services:
  nginx:
    environment:
      S_PIPES_EDITOR_REST_SERVICE_URL: "${S_PIPES_EDITOR_REST:-http://host.docker.internal:18115}"
    extra_hosts:
      - "host.docker.internal:host-gateway" # support "http://host.docker.internal" for Linux (Windows/Mac works without it)


  # Note, that for MacOS you migth need to set up DEBUG_TEMP_FOLDER=/var/folder, where the temporary files are created.
