const URLs = {
  SCRIPTS: `/scripts`,
  EXECUTION_HISTORY: `/execution/history`,
  EXECUTION: `/execution`,
  VIEWS_NEW: `/views/new`,
  SCRIPTS_DELETE: `/scripts/delete`,
  SCRIPTS_ONTOLOGIES: `/scripts/ontologies`,
  SCRIPTS_OWN_ONTOLOGY: `/scripts/own-ontology`,
  SCRIPTS_FORMS: `/scripts/forms`,
  FUNCTION_FORM: `/function/form`,
  SCRIPTS_CREATE: `/scripts/create`,
  LOAD_LOG: `/scripts/load-log`,
  SCRIPTS_FORMS_ANSWERS: `/scripts/forms/answers`,
  SCRIPTS_MODULES_DELETE: `/scripts/modules/delete`,
  SCRIPTS_DEPENDENCIES_DELETE: `/scripts/modules/dependencies/delete`,
  SCRIPTS_MODULES_MOVE: `/scripts/modules/move`,
  MODULE_TYPES: `/scripts/moduleTypes`,
  FUNCTION_SCRIPT: `/function/script`,
  FUNCTION_EXECUTE: `/function/execute`,
  FUNCTION_MODULE_EXECUTE: `/function/module/execute`,
  SCRIPTS_MODULE_DEPENDENCY: `/scripts/modules/dependency`,
  SCRIPTS_VALIDATE: `/scripts/validate`,
  EXECUTION_HISTORY_MODULES: `/execution/history-modules`,
  DEBUG_EXECUTIONS: `/log/executions`,
  DEBUG_TRIPLE_ORIGIN: `/log/triple-origin`,
  DEBUG_TRIPLE_ELIMINATION: `/log/triple-elimination`,
  DEBUG_VARIABLE_ORIGIN: `/log/variable-origin`,
};

export default URLs;
